services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - app_network

  db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpass
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:
    
networks:
  app_network:  
    
